### ISSUE TITLE
Where is the latest stable release for production usage?

### ISSUE THREAD

**Issue by fullenw1** [gaelcolas/datum#72]
The  GitHub PSD1 file says the module version is 0.0.1.
[https://github.com/gaelcolas/datum/blob/master/datum/datum.psd1](https://github.com/gaelcolas/datum/blob/master/datum/datum.psd1)

And when I type
`Find-Module -Name Datum`
PowerShell Gallery answers me that the module version is 0.0.38
but also the description says it is an **experimental module**…

The **README.md** says that v1.0.0 is aimed to be released for April 2018, or earlier…

Where can I find the latest stable version for production usage?

**Comment by gaelcolas** [comment]
Hi,

The version in psd1 is updated when released by the build release for every push to master (or most).

What's in master correspond to the latest version on the gallery, hence 0.0.38.

It's an experiment, and a rather successful one, that is being used in production by several companies.
The main reason for not going 1.0.0 yet is to follow semver, and allow breaking changes without major increment. The quality of the module is also lacking help, tests, and documentation.

That doesn't mean I intend to break it, but the current public interface is not optimal and I **may** change it. If you follow example of usage, such as what's done in the AutomatedLab DscWorkshop, you should not be affected as I try to be backward compatible.

I should update the readme, thanks. That was the plan, but life happened, and on only released smaller changes.

The version on the gallery is the latest, and as with all free & open source projects, production quality is not guaranteed and subjective to your environment.
It's in use by many, including customers I do not want to annoy too much with breaking changes.

Hope that helps, and you find this module useful.

**Comment by fullenw1** [comment]
Thanks for the clarification!
