### ISSUE TITLE
Confusing dates in readme

### ISSUE THREAD

**Issue by Stephanevg** [gaelcolas/datum#76]
This is really a minor thing:

In the readme it says:

```
A stable v1 release is expected for March 2018, while some concepts are thought through, and prototype code refactored.

```

Today it is november 2019, which is faaaar after march 2018 ;)
Perhaps it would make sense to update this to reflect what the reality of today is? (what is the latest version etc...). 
Or remove that sentence?

**Comment by gaelcolas** [comment]
done.
Also switched to newer version of pipeline, so it's much easier to release.
